name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          exit 1
      - name: Notify
        if: failure()
        uses: dojineko/slack-notify@v1
        with:
          job_status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          suffix_for_failure: @ryuichi1208
